version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials file as read-only
    env_file: 
      - .env  # Load environment variables from the .env file
    environment:
      - AWS_REGION=us-east-1






   
