name: Deploy to EC2 with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Images with Docker Compose
      run: |
        export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
        docker compose build
        docker compose push

    # Deploy to EC2
    - name: Verify SSH Connection
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Testing SSH connection to EC2 instance..."
          hostname
          echo "SSH connection verified successfully!"

    - name: Deploy Application to EC2 with Docker Compose
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          # Set up AWS credentials
          echo "Setting up AWS credentials for the session..."
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
          export AWS_DEFAULT_REGION=us-east-1

          # Stop and remove old containers
          echo "Stopping and removing existing containers (if any)..."
          docker compose down || true

          # Pull updated Docker images
          echo "Pulling the latest images..."
          docker compose pull

          # Start the application
          echo "Starting the updated application with Docker Compose..."
          docker compose up -d

          echo "Deployment complete!"
