name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/cpp-web:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cpp-web:latest

    # Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          # Stop and remove the old container
          docker stop cpp-web || true
          docker rm cpp-web || true

          # Pull the new image
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cpp-web:latest

          # Start a new container
          docker run -d --name cpp-web -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/cpp-web:latest
